### ISSUE TITLE
weird errors when supplying multiple maps and not matching timesteps

### ISSUE THREAD

**Issue by rroelz** [janablechschmidt/MetaRange.jl#50]
When setting up a simulation and `timesteps` doesn't match the number of maps weird things happen.  
Either it being too few, where it doesn't throw an error or too many where I get the baffling: 
```text
ERROR: KeyError: key "key" not found
Stacktrace:
 [1] getindex
   @ ./dict.jl:484 [inlined]
 [2] read_ls(env_dir::String, env_attib::Dict{String, String}, env_restr::Dict{String, String}, timesteps::Int64)
   @ MetaRange ~/.julia/dev/MetaRange/src/initialization_functions.jl:521
 [3] read_input(config_path::String)
   @ MetaRange ~/.julia/dev/MetaRange/src/read_input.jl:10
 [4] top-level scope
   @ REPL[2]:1
```
We should probably have:
- a more informative error message as this is one I feel will be run into often
- a general sanity check on the sanity checks
- separate sanity check functions so we can test and figure them out better

**Comment by janablechschmidt** [comment]
This error occurs in read_ls(), specifically in the sanity check starting in line 491, which is supposed to "check if sizes of all inputs match". There is an informative error message, the error just occurs before we get to it 😂 
Since the error is caused by `for key in keys(all_properties)` it might be worth running through the debugger and check what 'all_properties' actually contains
